### ISSUE TITLE
A SDK está funcionando?

### ISSUE THREAD

**Issue by cesar1983** [vindi/vindi-php#42]
Bom dia. Sou cliente da VINDI. Responsável pelo TI da empresa hqbeds, usamos a plataforma de vocês para cobrar nossos clientes.

Quero integrar nossa base de clientes com a ferramenta de vocês. Estou tentando utilizar a SDK em PHP, porém não está funcionando. Fiz um teste bem simples, instalando via composer e chamando o executando o programa abaixo : 

Estou com php 5.6 aqui..

```
<?php

require __DIR__.'/vendor/autoload.php';

$config['VINDI_API_KEY'] = 'xxxxxxxxxxxxxxxxxxxxxxxxx';
$config['VINDI_API_URI'] = 'https://app.vindi.com.br/api/v1';

$customerService = new Vindi\Customer($config);

$customers = $customerService->all([
    'sort_by'    => 'created_at',
    'sort_order' => 'desc'
]);

echo '<pre>';
print_r($customers);
?>

```

Não funciona..   O token está certinho, estou testando via chamada CURL direto aqui e está tudo okay, mas a SDK não rola....

( ! )  Fatal error: Uncaught exception 'Vindi\Exceptions\RequestException' in  /Users/cesar/Dev/php/vindi_teste/vendor/vindi/vindi-php/src/ApiRequester.php  on line 112
--
1 | 0.0101 | 239872 | {main}(  ) | .../index.php:0
2 | 0.1343 | 440936 | Vindi\Resource->all(  ) | .../index.php:25
3 | 0.1343 | 441480 | Vindi\ApiRequester->request(  ) | .../Resource.php:67
4 | 0.9384 | 662616 | Vindi\ApiRequester->response(  ) | .../ApiRequester.php:53
5 | 0.9385 | 663536 | Vindi\ApiRequester->checkForErrors(  ) | .../ApiRequester.php:72

**Comment by cesar1983** [comment]
$customerService está gerando normal tbm... na hoa de chamar algum método que voa...


```
> Vindi\Customer Object
> (
>     [apiRequester] => Vindi\ApiRequester Object
>         (
>             [client] => Vindi\Http\Client Object
>                 (
>                     [config:GuzzleHttp\Client:private] => Array
>                         (
>                             [base_uri] => GuzzleHttp\Psr7\Uri Object
>                                 (
>                                     [scheme:GuzzleHttp\Psr7\Uri:private] => https
>                                     [userInfo:GuzzleHttp\Psr7\Uri:private] => 
>                                     [host:GuzzleHttp\Psr7\Uri:private] => app.vindi.com.br
>                                     [port:GuzzleHttp\Psr7\Uri:private] => 
>                                     [path:GuzzleHttp\Psr7\Uri:private] => /api/v1
>                                     [query:GuzzleHttp\Psr7\Uri:private] => 
>                                     [fragment:GuzzleHttp\Psr7\Uri:private] => 
>                                 )
> 
>                             [auth] => Array
>                                 (
>                                     [0] => xxxxxxxxxx....
>                                     [1] => 
>                                     [2] => BASIC
>                                 )
> 
>                             [headers] => Array
>                                 (
>                                     [Content-Type] => application/json
>                                     [User-Agent] => Vindi-PHP/1.1.0; 127.0.0.1
>                                 )
> 
>                             [verify] => /Users/cesar/Dev/php/vindi_teste/vendor/vindi/vindi-php/data/ssl/ca-bundle.crt
>                             [timeout] => 60
>                             [curl.options] => Array
>                                 (
>                                     [CURLOPT_SSLVERSION] => CURL_SSLVERSION_TLSv1_2
>                                 )
> 
>                             [handler] => GuzzleHttp\HandlerStack Object
>                                 (
>                                     [handler:GuzzleHttp\HandlerStack:private] => Closure Object
>                                         (
>                                             [static] => Array
>                                                 (
>                                                     [default] => Closure Object
>                                                         (
>                                                             [static] => Array
>                                                                 (
>                                                                     [default] => GuzzleHttp\Handler\CurlMultiHandler Object
>                                                                         (
>                                                                             [factory:GuzzleHttp\Handler\CurlMultiHandler:private] => GuzzleHttp\Handler\CurlFactory Object
>                                                                                 (
>                                                                                     [handles:GuzzleHttp\Handler\CurlFactory:private] => Array
>                                                                                         (
>                                                                                         )
> 
>                                                                                     [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 50
>                                                                                 )
> 
>                                                                             [selectTimeout:GuzzleHttp\Handler\CurlMultiHandler:private] => 1
>                                                                             [active:GuzzleHttp\Handler\CurlMultiHandler:private] => 
>                                                                             [handles:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
>                                                                                 (
>                                                                                 )
> 
>                                                                             [delays:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
>                                                                                 (
>                                                                                 )
> 
>                                                                         )
> 
>                                                                     [sync] => GuzzleHttp\Handler\CurlHandler Object
>                                                                         (
>                                                                             [factory:GuzzleHttp\Handler\CurlHandler:private] => GuzzleHttp\Handler\CurlFactory Object
>                                                                                 (
>                                                                                     [handles:GuzzleHttp\Handler\CurlFactory:private] => Array
>                                                                                         (
>                                                                                         )
> 
>                                                                                     [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 3
>                                                                                 )
> 
>                                                                         )
> 
>                                                                 )
> 
>                                                             [parameter] => Array
>                                                                 (
>                                                                     [$request] => 
>                                                                     [$options] => 
>                                                                 )
> 
>                                                         )
> 
>                                                     [streaming] => GuzzleHttp\Handler\StreamHandler Object
>                                                         (
>                                                             [lastHeaders:GuzzleHttp\Handler\StreamHandler:private] => Array
>                                                                 (
>                                                                 )
> 
>                                                         )
> 
>                                                 )
> 
>                                             [parameter] => Array
>                                                 (
>                                                     [$request] => 
>                                                     [$options] => 
>                                                 )
> 
>                                         )
> 
>                                     [stack:GuzzleHttp\HandlerStack:private] => Array
>                                         (
>                                             [0] => Array
>                                                 (
>                                                     [0] => Closure Object
>                                                         (
>                                                             [parameter] => Array
>                                                                 (
>                                                                     [$handler] => 
>                                                                 )
> 
>                                                         )
> 
>                                                     [1] => http_errors
>                                                 )
> 
>                                             [1] => Array
>                                                 (
>                                                     [0] => Closure Object
>                                                         (
>                                                             [parameter] => Array
>                                                                 (
>                                                                     [$handler] => 
>                                                                 )
> 
>                                                         )
> 
>                                                     [1] => allow_redirects
>                                                 )
> 
>                                             [2] => Array
>                                                 (
>                                                     [0] => Closure Object
>                                                         (
>                                                             [parameter] => Array
>                                                                 (
>                                                                     [$handler] => 
>                                                                 )
> 
>                                                         )
> 
>                                                     [1] => cookies
>                                                 )
> 
>                                             [3] => Array
>                                                 (
>                                                     [0] => Closure Object
>                                                         (
>                                                             [parameter] => Array
>                                                                 (
>                                                                     [$handler] => 
>                                                                 )
> 
>                                                         )
> 
>                                                     [1] => prepare_body
>                                                 )
> 
>                                         )
> 
>                                     [cached:GuzzleHttp\HandlerStack:private] => 
>                                 )
> 
>                             [allow_redirects] => Array
>                                 (
>                                     [max] => 5
>                                     [protocols] => Array
>                                         (
>                                             [0] => http
>                                             [1] => https
>                                         )
> 
>                                     [strict] => 
>                                     [referer] => 
>                                     [track_redirects] => 
>                                 )
> 
>                             [http_errors] => 1
>                             [decode_content] => 1
>                             [cookies] => 
>                         )
> 
>                 )
> 
>             [lastResponse] => 
>             [lastOptions] => 
>         )
> 
> )
```

**Comment by cesar1983** [comment]
Achei o problema.. era uma coisa idiota.

A "/" no final da url faz toda diferença....

'https://app.vindi.com.br/api/v1';

**Comment by rtakauti** [comment]
@cesar1983 Qualquer dúvida estamos a disposição :smiley:

**Comment by venturion** [comment]
> Achei o problema.. era uma coisa idiota.
> 
> A "/" no final da url faz toda diferença....
> 
> 'https://app.vindi.com.br/api/v1';

Salvou meu dia kkk

**Comment by ftjr20** [comment]
no meu caso estava funcionando perfeitamente e parou do nada...achei que fosse atualização do php, passei p o 7.3 e o erro persiste se alguém der uma luz agradeço


Fatal error: Uncaught Vindi\Exceptions\RequestException in .......\vendor\vindi\vindi-php\src\ApiRequester.php:126 Stack trace: 
#0 .......\vendor\vindi\vindi-php\src\ApiRequester.php(86): Vindi\ApiRequester->checkForErrors(Object(GuzzleHttp\Psr7\Response), Array) 
#1 .......\vendor\vindi\vindi-php\src\ApiRequester.php(61): Vindi\ApiRequester->response(Object(GuzzleHttp\Psr7\Response)) 
#2 .......\vendor\vindi\vindi-php\src\Resource.php(121): Vindi\ApiRequester->request('PUT', 'customers/11...', Array) 
#3 runtest.php(16841): Vindi\Resource->update('5655', Array) 
#6 {main} thrown in .......\vendor\vindi\vindi-php\src\ApiRequester.php on line 126

**Comment by laerte-guimaraes** [comment]
@ftjr20 consegue verificar o retorno dessa requisição para tentarmos entender o erro na resposta?

Atualmente qualquer resposta onde o status HTTP seja 5xx ou 4xx serão capturadas pelo método em:
https://github.com/vindi/vindi-php/blob/e2c62b5b7028ccbc1b86618bdc1ac5a6e94d0cee/src/ApiRequester.php#L121

E uma exceção será lançada. Para entendermos melhor o motivo, é necessário capturar o erro e logar/exibir os dados presentes. Consegue validar? 😉

**Comment by michaellothbrook** [comment]
> Achei o problema.. era uma coisa idiota.
> 
> A "/" no final da url faz toda diferença....
> 
> 'https://app.vindi.com.br/api/v1';

pô cara, vc me salvou tbm, vlwwww
